version: "3"

services:
    postgres:
        image: postgres:9.4-alpine
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: app
            POSTGRES_PASSWORD: app 
